---
name: Dependabot Automerge

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    name: Dependabot Automerge
    uses: miikkak/workflows/.github/workflows/dependabot-automerge.yml@75031271bcdf5e0187fa0f8011fd7374270e6e94 # main
    secrets:
      PULL_REQUEST_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
