---
name: PR Check

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  pre-commit:
    uses: miikkak/workflows/.github/workflows/pr-check.yml@75031271bcdf5e0187fa0f8011fd7374270e6e94 # main
    secrets: inherit
