---
name: Scheduled Security Scan

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  security:
    uses: miikkak/workflows/.github/workflows/security-scan.yml@75031271bcdf5e0187fa0f8011fd7374270e6e94 # main
    secrets: inherit
